/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package it.taccuino.view;

import it.taccuino.controller.TaccuinoJpaController;
import it.taccuino.controller.exceptions.NonexistentEntityException;
import it.taccuino.model.Taccuino;

import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * 
 * @author gabrieleposca
 */
public class Home extends javax.swing.JFrame {

	private DefaultTableModel model;

	public Home() {
		initComponents();

		// Tabella
		model = new DefaultTableModel() {
			public boolean isCellEditable(int rowIndex, int colIndex) {
				return false; // Disallow the editing of any cell
			}
		};
		TaccuinoJpaController taccuinoJpaController = new TaccuinoJpaController();
		List<Taccuino> listaTaccuini = taccuinoJpaController
				.findTaccuinoEntities();
		int i = 0;
		String[] header = { "Id", "Nome" };
		model.setColumnIdentifiers(header);
		model.setColumnCount(2);
		for (Iterator<Taccuino> it = listaTaccuini.iterator(); it.hasNext(); i++) {
			Taccuino tmp = it.next();
			model.setRowCount(model.getRowCount() + 1);
			model.setValueAt(tmp.getId(), i, 0);
			model.setValueAt(tmp.getTitolo().toString(), i, 1);
		}
		tableTaccuini.setModel(model);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		tableTaccuini = new javax.swing.JTable();
		buttonCancella = new javax.swing.JButton();
		buttonDettagli = new javax.swing.JButton();
		buttonAggiungi = new javax.swing.JButton();
		buttonModifica = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
		jLabel1.setText("Elenco Taccuini");

		jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

		tableTaccuini.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
		tableTaccuini.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null },
						{ null, null }, { null, null } }, new String[] { "Id",
						"Nome" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		tableTaccuini.setRowHeight(20);
		jScrollPane1.setViewportView(tableTaccuini);

		buttonCancella.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/Images/delete.png"))); // NOI18N
		buttonCancella.setToolTipText("Cancella");
		buttonCancella.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				buttonCancellaMouseClicked(evt);
			}
		});

		buttonDettagli.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/Images/dettagli.png"))); // NOI18N
		buttonDettagli.setToolTipText("Dettagli");
		buttonDettagli.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				buttonDettagliMouseClicked(evt);
			}
		});

		buttonAggiungi.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/Images/insert.png"))); // NOI18N
		buttonAggiungi.setToolTipText("Aggiungi");
		buttonAggiungi.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				buttonAggiungiMouseClicked(evt);
			}
		});

		buttonModifica.setIcon(new javax.swing.ImageIcon(getClass()
				.getResource("/Images/update.png"))); // NOI18N
		buttonModifica.setToolTipText("Modifica");
		buttonModifica.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				buttonModificaMouseClicked(evt);
			}
		});

		org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel2Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel2Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(jScrollPane1,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												589, Short.MAX_VALUE)
										.add(jPanel2Layout
												.createSequentialGroup()
												.add(0, 0, Short.MAX_VALUE)
												.add(buttonDettagli)
												.add(18, 18, 18)
												.add(buttonAggiungi)
												.add(18, 18, 18)
												.add(buttonModifica)
												.add(18, 18, 18)
												.add(buttonCancella)))
								.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(jPanel2Layout
								.createSequentialGroup()
								.addContainerGap()
								.add(jPanel2Layout
										.createParallelGroup(
												org.jdesktop.layout.GroupLayout.LEADING)
										.add(buttonCancella)
										.add(buttonDettagli)
										.add(buttonAggiungi)
										.add(buttonModifica))
								.addPreferredGap(
										org.jdesktop.layout.LayoutStyle.RELATED)
								.add(jScrollPane1,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										366,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.addContainerGap()
						.add(jLabel1)
						.addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE))
				.add(org.jdesktop.layout.GroupLayout.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)
								.add(jPanel2,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup()
						.addContainerGap()
						.add(jLabel1)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jPanel2,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void buttonCancellaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonCancellaMouseClicked
		int rowIndex = tableTaccuini.getSelectedRow();
		String id = tableTaccuini.getValueAt(rowIndex, 0).toString();
		Object[] options = { "Si", "No" };
		JOptionPane optionPane = new JOptionPane();
		int value = optionPane.showOptionDialog(this,
				"Sei sicuro di cancellare il taccuino?", "Attenzione",
				JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE,
				null, options, "No");
		if (value == JOptionPane.YES_OPTION) {
			TaccuinoJpaController taccuinoJpaController = new TaccuinoJpaController();
			if (taccuinoJpaController.countNoteByTaccuinoId(id) == 0) {
				try {
					taccuinoJpaController.destroy(Long.parseLong(id, 10));
				} catch (NonexistentEntityException ex) {
					Logger.getLogger(Home.class.getName()).log(Level.SEVERE,
							null, ex);
				}
				JOptionPane.showMessageDialog(this,
						"Taccuino cancellato correttamente", "Info", 1);
				model.removeRow(rowIndex);
				tableTaccuini.setModel(model);
			} else {
				JOptionPane
						.showMessageDialog(
								this,
								"Il taccuino non pu�� essere cancellato in quanto vi sono associate una o pi�� note. Per procedere nell'operazione consultare l'amministratore di sistema.",
								"Attenzione", JOptionPane.WARNING_MESSAGE);
			}
		}
	}// GEN-LAST:event_buttonCancellaMouseClicked

	private void buttonDettagliMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonDettagliMouseClicked
		int rowIndex = tableTaccuini.getSelectedRow();
		String id = tableTaccuini.getValueAt(rowIndex, 0).toString();
		DettagliTaccuino formDettagliTaccuino = new DettagliTaccuino(id);
		formDettagliTaccuino.setVisible(true);
	}// GEN-LAST:event_buttonDettagliMouseClicked

	private void buttonAggiungiMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonAggiungiMouseClicked
		String titolo;
		titolo = JOptionPane.showInputDialog(null,
				"Inserisci il titolo del taccuino", "");
		if (titolo != null) {
			Taccuino t = new Taccuino();
			t.setTitolo(titolo);
			TaccuinoJpaController taccuinoJpaController = new TaccuinoJpaController();
			taccuinoJpaController.create(t);
			JOptionPane.showMessageDialog(this,
					"Taccuino creato correttamente", "Info", 1);
			int row = tableTaccuini.getRowCount();
			model.setRowCount(model.getRowCount() + 1);
			model.setValueAt(t.getId(), row, 0);
			model.setValueAt(t.getTitolo().toString(), row, 1);
			tableTaccuini.setModel(model);
		}
	}// GEN-LAST:event_buttonAggiungiMouseClicked

	private void buttonModificaMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_buttonModificaMouseClicked
		String titolo;
		int rowIndex = tableTaccuini.getSelectedRow();
		String id = tableTaccuini.getValueAt(rowIndex, 0).toString();
		titolo = JOptionPane.showInputDialog(null,
				"Inserisci il titolo del taccuino", "");
		if (titolo != null) {
			TaccuinoJpaController taccuinoJpaController = new TaccuinoJpaController();
			Taccuino t = taccuinoJpaController.findTaccuino(Long.parseLong(id,
					10));
			t.setTitolo(titolo);
			try {
				taccuinoJpaController.edit(t);
			} catch (NonexistentEntityException ex) {
				Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null,
						ex);
			} catch (Exception ex) {
				Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null,
						ex);
			}

			model.setValueAt(t.getId(), rowIndex, 0);
			model.setValueAt(t.getTitolo().toString(), rowIndex, 1);
			tableTaccuini.setModel(model);

			JOptionPane.showMessageDialog(this,
					"Taccuino modificato correttamente", "Info", 1);
		}
	}// GEN-LAST:event_buttonModificaMouseClicked

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Home.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Home().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton buttonAggiungi;
	private javax.swing.JButton buttonCancella;
	private javax.swing.JButton buttonDettagli;
	private javax.swing.JButton buttonModifica;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable tableTaccuini;
	// End of variables declaration//GEN-END:variables
}
